/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreatenoteRouteImport } from './routes/createnote'
import { Route as IndexRouteImport } from './routes/index'

const CreatenoteRoute = CreatenoteRouteImport.update({
  id: '/createnote',
  path: '/createnote',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createnote': typeof CreatenoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createnote': typeof CreatenoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/createnote': typeof CreatenoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/createnote'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/createnote'
  id: '__root__' | '/' | '/createnote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatenoteRoute: typeof CreatenoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/createnote': {
      id: '/createnote'
      path: '/createnote'
      fullPath: '/createnote'
      preLoaderRoute: typeof CreatenoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatenoteRoute: CreatenoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
